# Generated by Django 5.2 on 2025-05-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                error_messages={
                    "invalid": "Invalid value",
                    "invalid_choice": "Select a valid choice. That choice is not one of the available choices.",
                    "invalid_pk_value": "Invalid primary key value",
                    "null": "This field cannot be null",
                },
                related_name="todos",
                to="todo_app.tag",
            ),
        ),
    ]
