# Generated by Django 5.2 on 2025-05-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0002_alter_todo_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("C", "Completed"), ("A", "Archived")],
                db_index=True,
                default="P",
                error_messages={
                    "invalid_choice": "Please choose one of the following options: P: Pending, C: Completed, A: Archived."
                },
                max_length=255,
            ),
        ),
    ]
