# Generated by Django 5.2 on 2025-05-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0005_alter_todo_status_alter_todo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("C", "Completed"), ("A", "Archived")],
                db_index=True,
                default="P",
                error_messages={
                    "invalid_choice": "Please choose one of the following options: P: Pending, C: Completed, A: Archived."
                },
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(
                db_index=True,
                error_messages={
                    "blank": "This field cannot be blank",
                    "invalid": "Invalid value",
                    "max_length": "Ensure this value has at most 255 characters",
                    "null": "This field cannot be null",
                },
                max_length=255,
            ),
        ),
    ]
