# Generated by Django 5.2 on 2025-05-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(
                db_index=True,
                error_messages={
                    "blank": "Title field cannot be empty.",
                    "invalid": "Please enter a valid title.",
                    "max_length": "Title must be at most 255 characters long.",
                    "null": "Title field cannot be null.",
                    "required": "Please enter a blog post title.",
                },
                max_length=255,
                unique=True,
            ),
        ),
    ]
